[package]
name = "core-graphics"
description = "Bindings to Core Graphics for OS X"
homepage = "https://github.com/servo/core-graphics-rs"
repository = "https://github.com/servo/core-graphics-rs"
version = "0.4.1"
authors = ["The Servo Project Developers"]
license = "MIT / Apache-2.0"

[dependencies]
core-foundation-sys = {path = "../core-foundation-rs/core-foundation-sys"}
